# Generated by Django 5.0 on 2024-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
