# Generated by Django 5.0 on 2024-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapboxapp', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
