# Generated by Django 4.2.7 on 2024-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to='images'),
        ),
    ]
